### ISSUE TITLE
TDU Ultra Community pack 1.68b traffic crush

### ISSUE THREAD

**Issue by OL333H** [djey47/tdu-cp#4]
The game doesn't generate traffic, and after starting a race crushes.

**Comment by OL333H** [comment]
After patching to 2.00 A all become OK.

**Comment by Tequiller** [comment]
Ask to reopen ticket:
Game updated to 1.66 + Megapack + version 2.00A Full:
Should be ok then suddenly no new traffic.

If we teleport to other area no more traffic.
If we change profil, game crash.

*Know that game also crash sometimes when opening map or closing map (issue: [https://github.com/djey47/tdu-cp/issues/8](https://github.com/djey47/tdu-cp/issues/8)).

**Comment by djey47** [comment]
No need to reopen, unless someone will maintain the project again. For traffic issues try enabling vsync. Tducp did not alter traffic behaviour ( because of some issues in 1.68b).
