### ISSUE TITLE
404 link in repo description

### ISSUE THREAD

**Issue by slrslr** [djey47/tdu-cp#6]
i think that the link in this repository description no longer works
working one may be: https://turboduck.net/forums/topic/33842-djey-tdu-community-patch-200a/

**Comment by kmartin91** [comment]
Hi, Thanks, link has been changed by https://turboduck.net/forums/forum/73-tdu-mod-shop/ (instead https://turboduck.net/forums/forum/51-tdu-mod-shop/ )
